### ISSUE TITLE
Meteoriks page new translations

### ISSUE THREAD

**Issue by lunasorcery** [lunasorcery/executable.graphics#10]
I've added support for Honorable Mentions into the [meteorik-honorable-mentions](https://github.com/lunasorcery/executable.graphics/tree/meteorik-honorable-mentions) branch, but the string `badges.meteorik-runnerup` needs to be translated into the other languages before I can push it live.

https://github.com/lunasorcery/executable.graphics/blob/b0bc7e8580e124bc7cc3fef252d70eb9908e6288/languages/en.json#L21

Additionally, since we've now had multiple Best Executable Graphics winners, the ending of `meteoriks.what-are-meteoriks-p2` needs to be pluralized ("winner" -> "winners").

https://github.com/lunasorcery/executable.graphics/blob/c2d3c0796796af56e09f0829dfa6b7b349cd88da/languages/en.json#L27

Current progress:
- [X] EN (@lunasorcery)
- [x] FR (@totetmatt, @Lia-Sae, @nnorm)
- [x] DE (@slerpyyy)
- [x] NL (@PoroCYon)
- [x] PT (@psenough)
- [x] ES (@bitnenfer)

(also, no rush!)

**Comment by PoroCYon** [comment]
I think slerpy picked up my translation along the way?
